apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tls
spec:
  secretName: portfolio-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
    group: cert-manager.io
  dnsNames:
    - malashikh.in
    - www.malashikh.in
