apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml

commonLabels:
  app.kubernetes.io/part-of: portfolio
  app.kubernetes.io/managed-by: kustomize

images:
  - name: portfolio
    newName: ghcr.io/themdq/malashikh.in
    newTag: latest
